version: '3.8'

services:
  desafio-tecnico-objective-raylan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-tecnico-objective-raylan
    ports:
      - "8000:80"  # Mapeamento da porta do host para o contêiner (altere conforme necessário)
    volumes:
      - .:/var/www  # Mapeamento do diretório local para o diretório do contêiner
