version: '3.8'

services:
  desafio-tecnico-objective-raylan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-tecnico-objective-raylan
    ports:
      - "8000:80"  # Mapeamento da porta do host para o contêiner (altere conforme necessário)
    volumes:
      - ./laravel:/var/www  # Mapeamento do diretório local 'laravel' para o diretório do contêiner
    command: >
      bash -c 'while ! mysqladmin ping -h"db" --silent; do sleep 1; done &&
      if [ ! -d "/var/www/vendor" ]; then composer install; fi &&
      php /var/www/artisan serve --host=0.0.0.0 --port=80' &&
      php /var/www/artisan migrate &&
      php /var/www/artisan db:seed
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: desafio-tecnico-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'objective'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
